; This file was auto-generated by drush make
core = 7.x

api = 2
projects[] = drupal

; Modules

projects[admin_menu][subdir] = "contrib"
projects[backup_migrate][subdir] = "contrib"
projects[better_exposed_filters][subdir] = "contrib"
projects[block_class][subdir] = "contrib"
projects[ctools][subdir] = "contrib"
projects[ckeditor][subdir] = "contrib"
projects[ckeditor][ckeditor_media] = "contrib"
projects[date][subdir] = "contrib"
projects[devel][subdir] = "contrib"
projects[ds][subdir] = "contrib"
projects[ds_bootstrap_layouts][subdir] = "contrib"
projects[entity][subdir] = "contrib"
projects[features][subdir] = "contrib"
projects[field_collection][subdir] = "contrib"
projects[field_group][subdir] = "contrib"
projects[filefield_sources][subdir] = "contrib"
projects[filter_perms][subdir] = "contrib"
projects[image_link_formatter][subdir] = "contrib"
projects[job_scheduler][subdir] = "contrib"
projects[jquery_update][subdir] = "contrib"
projects[libraries][subdir] = "contrib"
projects[link][subdir] = "contrib"
projects[media][subdir] = "contrib"
projects[menu_block][subdir] = "contrib"
projects[module_filter][subdir] = "contrib"
projects[pathauto][subdir] = "contrib"
projects[simplehtmldom][subdir] = "contrib"
projects[special_menu_items][subdir] = "contrib"
projects[token][subdir] = "contrib"
projects[views][subdir] = "contrib"
projects[views_bootstrap][subdir] = "contrib"

; Themes
projects[] = bootstrap

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.