; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.31"

; Modules
projects[admin_menu][subdir] = "contrib"
projects[admin_menu][version] = "3.0-rc4"

projects[backup_migrate][subdir] = "contrib"
projects[backup_migrate][version] = "3.0"

projects[better_exposed_filters][subdir] = "contrib"
projects[better_exposed_filters][version] = "3.0-beta4"

projects[block_class][subdir] = "contrib"
projects[block_class][version] = "2.1"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.4"

projects[ckeditor][subdir] = "contrib"
projects[ckeditor][version] = "1.15"

projects[date][subdir] = "contrib"
projects[date][version] = "2.8"

projects[devel][subdir] = "contrib"
projects[devel][version] = "1.5"

projects[ds][subdir] = "contrib"
projects[ds][version] = "2.6"

projects[ds_bootstrap_layouts][subdir] = "contrib"
projects[ds_bootstrap_layouts][version] = "3.x-dev"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.5"

projects[features][subdir] = "contrib"
projects[features][version] = "2.2"

projects[field_collection][subdir] = "contrib"
projects[field_collection][version] = "1.0-beta7"

projects[field_group][subdir] = "contrib"
projects[field_group][version] = "1.4"

projects[filefield_sources][subdir] = "contrib"
projects[filefield_sources][version] = "1.9"

projects[filter_perms][subdir] = "contrib"
projects[filter_perms][version] = "1.0"

projects[image_link_formatter][subdir] = "contrib"
projects[image_link_formatter][version] = "1.0"

projects[imce][subdir] = "contrib"
projects[imce][version] = "1.9"

projects[job_scheduler][subdir] = "contrib"
projects[job_scheduler][version] = "2.0-alpha3"

projects[jquery_update][subdir] = "contrib"
projects[jquery_update][version] = "2.4"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "2.2"

projects[link][subdir] = "contrib"
projects[link][version] = "1.2"

projects[menu_block][subdir] = "contrib"
projects[menu_block][version] = "2.4"

projects[module_filter][subdir] = "contrib"
projects[module_filter][version] = "2.0-alpha2"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.2"

projects[simplehtmldom][subdir] = "contrib"
projects[simplehtmldom][version] = "1.12"

projects[special_menu_items][subdir] = "contrib"
projects[special_menu_items][version] = "2.0"

projects[token][subdir] = "contrib"
projects[token][version] = "1.5"

projects[views][subdir] = "contrib"
projects[views][version] = "3.8"

projects[views_bootstrap][subdir] = "contrib"
projects[views_bootstrap][version] = "3.1"

; Themes
projects[bootstrap][version] = "3.0"

projects[framework][version] = "3.6"

; Themes
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[custom_bootstrap][download][type] = ""
projects[custom_bootstrap][download][url] = ""
projects[custom_bootstrap][type] = "theme"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ddcl][download][type] = ""
libraries[ddcl][download][url] = ""
libraries[ddcl][directory_name] = "ddcl"
libraries[ddcl][type] = "library"